name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build APK
        env:
          EXPO_TOKEN: ${{ i46IPRG33QJ929NQUGbQK_FJ117IKM3jiml9zIoh }}
        run: eas build -p android --profile preview --non-interactive
